learning_templates/ANLOSFIX/urls.py
from django.contrib import admin
from django.urls import path,include
from perusahaan import views as main_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main_views.IndexPerusahaan.as_view(),name='index'),
    path('register/',main_views.registercompany,name='create'),
    path('registerkaryawan/',main_views.registeruser,name='create_karyawan'),
    path('profile/',main_views.ProfilePerusahaan.as_view(),name='profile'),
    path('list/',main_views.ListKaryawan.as_view(),name='listkaryawan'),
    path('delete/<int:pk>/',main_views.ListKaryawanDeleteView.as_view(),name="delete"),
    path('<int:pk>/update/',main_views.ListKaryawanUpdateView.as_view(),name='update'),
    # path('<int:pk>/list/',main_views.DetailKaryawan.as_view(),name='listkaryawan'),
    path('login/',main_views.user_login,name='user_login'),
    path('logout/',main_views.user_logout,name='logout'),

]

learning_templates/perusahaan/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class company_privileges(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name
class company(models.Model):
    user = models.OneToOneField(User,related_name="company",on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    address = models.CharField(max_length=254)
    telp = models.CharField(max_length=12)
    location = models.TextField(max_length=256)

    def __str__(self):
        return self.name

class users(models.Model):
    # id_company = models.ForeignKey(company,on_delete=models.CASCADE,default='')
    # id_company = models.ManyToManyField(company)
    user = models.OneToOneField(User,related_name="users",on_delete=models.CASCADE,default="")
    id_company = models.IntegerField()
    name = models.CharField(max_length=254)
    # email = models.EmailField()
    telp = models.CharField(max_length=12)


    def __str__(self):
        return self.name

class presence(models.Model):
    id_user = models.IntegerField()
    date_presence = models.DateField()
    start_presence = models.TimeField()
    end_presence = models.TimeField()
    location = models.TextField(max_length=256)

class vacation (models.Model):
    id_user = models.ForeignKey(users,on_delete=models.CASCADE)
    start_day = models.DateField()
    end_day = models.DateField()

learning_templates/perusahaan/forms.py
from django import forms
from django.contrib.auth.models import User
from perusahaan.models import company,users

class CompanyForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password','groups')

class company(forms.ModelForm):
    class Meta():
        model = company
        fields = ('name','address','telp','location')

class users(forms.ModelForm):
    class Meta():
        model = users
        fields = ('id_company','name','telp')

learning_templates/perusahaan/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)
from perusahaan import models
from perusahaan.forms import company,CompanyForm,users
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def special (request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

    
class IndexPerusahaan(ListView):
    model = models.company
    template_name = 'index.html'

def registercompany(request):
    registered = False
    
    if request.method == "POST":
        user_form = CompanyForm(data=request.POST)
        profile_form = company(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # if 'profile_pic' in request.FILES:
            #     profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = CompanyForm()
        profile_form = company()

    return render(request,'perusahaan_form.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def registeruser(request):
    registered = False
    
    if request.method == "POST":
        user_form = CompanyForm(data=request.POST)
        profile_form = users(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # if 'profile_pic' in request.FILES:
            #     profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = CompanyForm()
        profile_form = users()

    return render(request,'karyawan_form.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    context_object_name = 'data_login'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'login.html',{'name' : request.user.username })


class ProfilePerusahaan(ListView):
    context_object_name = 'profilperusahaan'
    model = models.company
    model = models.users
    template_name = 'profile.html'

class ListKaryawan(ListView):
    context_object_name = 'listkaryawans'
    model = models.users
    template_name = 'karyawan_list.html'

class ListKaryawanDeleteView(DeleteView):
    context_object_name = 'listkaryawans'
    model = models.users
    template_name = 'karyawan_confirm_delete.html'
    success_url = reverse_lazy('listkaryawan')

class ListKaryawanUpdateView(UpdateView):
    fields = ('name','telp')
    model = models.users
    template_name = 'karyawan_update.html'
    success_url = reverse_lazy('listkaryawan')

learning_templates/templates/base.html
<!doctype html>

{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'css/geolocation.css' %}">

    <title>ANLOSIA</title>
</head>
<style>
    .bg-custom {
        background-color: #5A1DBF;
    }

    a.nav-link {
        color: white !important;
    }
</style>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-custom">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                {% if perms.perusahaan %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listkaryawan' %}">Karyawan</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Reimbursement</a>
                </li>
                {% if perms.perusahaan %}
                <li class="nav-item">
                    <a class="nav-link" href={% url 'profile' %}>Profile</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Todo</a>
                </li>
                {% if perms.perusahaan %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_karyawan' %}">Buat Karyawan</a>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right ml-auto">
                {% if user.is_authenticated  %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">LOG OUT</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if perms.perusahaan %}
    Anda adalah Admin
    {% else %}
    Anda adalah Karyawan
    {% endif %}
    {% block body_block %}
    {% endblock body_block %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js">
    </script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({
                responsive: true
            });
        });
    </script>
    <script
        src='https://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=geometry,drawing&amp;ext=.js&amp;key=AIzaSyC4NCAi9sAjWxAJ89h52Ot37vyoow9CZDI'>
    </script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

learning_templates/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Selamat Anda Berhasil Membuat</h1>
{% endblock body_block %}

learning_templates/templates/karyawan_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Delete {{listkaryawans.name}}?</h1>
<form action="" method="post">
    {% csrf_token %}
    <input name="" id="" class="btn btn-danger" type="submit" value="Delete">
    {% comment %} <a href="{% url 'detail' pk=data.pk %}">Cancel</a> {% endcomment %}
</form>

{% endblock body_block %}

learning_templates/templates/karyawan_form.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center">
            <h1>Data Karyawan</h1>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <input type="text" name="groups" id="id_groups" value="4">
                <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150"
                        required="" id="id_username"></p>
                <p><label for="id_email">Email address:</label> <input type="email" name="email" maxlength="254"
                        id="id_email"></p>
                <p><label for="id_password">Password:</label> <input type="password" name="password" required=""
                        id="id_password"></p>
                {% comment %} {{user_form.as_p}} {% endcomment %}
            </div>
            <div class="col">
                <input type="text" name="id_company" id="id_id_company" value="{{user.company.id}}">
                <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="254" required=""
                        id="id_name"></p>
                <p><label for="id_telp">Telp:</label> <input type="text" name="telp" maxlength="12" required=""
                        id="id_telp"></p>
                {% comment %} {{profile_form.as_p}} {% endcomment %}
            </div>
        </div>
        <br>
        <div class="text-center">
            <input type="submit" value="Submit">
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

learning_templates/templates/karyawan_list.html
<!doctype html>
{% extends 'base.html' %}
{% block body_block %}

{% if user.is_authenticated %}
<div class="container">
    <table class="display" id="table_id">
        <thead>
            <tr class="text-center">
                <th scope="col">Username</th>
                <th scope="col">email</th>
                <th scope="col">Nama</th>
                <th scope="col">Telpon</th>
                <th scope="col">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {% for listkaryawan in listkaryawans%}
            {% if user.company.id == listkaryawan.id_company %}
            <tr class="text-center">
                <td>{{listkaryawan.user}}</td>
                <td>{{listkaryawan.user.email}}</td>
                <td>{{listkaryawan.name}}</td>
                <td>{{listkaryawan.telp}}</td>
                <td><a class="btn btn-primary" href="{% url 'update' pk=listkaryawan.pk %}" role="button">Edit</a>
                    <a class="btn btn-primary" href="#" role="button">Detail</a>
                    <a class="btn btn-primary" href="{% url 'delete' pk=listkaryawan.pk %}" role="button">Delete</a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
Anda Belum Login
{% endif %}
{% endblock %}

learning_templates/templates/karyawan_update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock body_block %}

learning_templates/templates/login.html
{% extends 'base.html' %}
<!doctype html>
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Email:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" value="Login">
    </form>

</div>
{% endblock body_block %}

learning_templates/templates/perusahaan_form.html
{% extends 'base.html' %}
{% block body_block %}
<style>
    #tool {
        width: 100%;
        display: inline-flex;
    }

    #map_canvas {
        height: 300px;
        width: 50%;
        margin-right: 10px;
        padding: 0px;
    }

    #info {
        width: 50%;
        float: left;
        height: 270px;
        overflow: scroll;
    }
</style>
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center">
            <h1>Data Perusahaan</h1>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <input type="text" name="groups" id="id_groups" value="3">
                <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150"
                        required="" id="id_username"></p>
                <p><label for="id_email">Email address:</label> <input type="email" name="email" maxlength="254"
                        id="id_email"></p>
                <p><label for="id_password">Password:</label> <input type="password" name="password" required=""
                        id="id_password"></p>
                {% comment %} {{user_form.as_p}} {% endcomment %}
            </div>
            <div class="col">
                <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="254" required=""
                        id="id_name"></p>
                <p><label for="id_address">Address:</label> <input type="text" name="address" maxlength="254"
                        required="" id="id_address"></p>
                <p><label for="id_telp">Telp:</label> <input type="text" name="telp" maxlength="12" required=""
                        id="id_telp"></p>
                {% comment %} <p><label for="id_location">Location:</label> <textarea name="location" cols="40"
                        rows="10" maxlength="256" required="" id="id_location"></textarea></p> {% endcomment %}

            </div>
            <div id="tool">
                <div id="map_canvas" style=" border: 2px solid #3872ac;"></div> <br>
                <textarea name="location" id="info" cols="30" rows="10"></textarea>
            </div>
        </div>
        <br>
        <div class="text-center">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>

{% endblock body_block %}

learning_templates/templates/profile.html
<!doctype html>
{% extends 'base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="container">
    <h1>Nama Lengkap {{user.company.name}}</h1>
    <h2>COMPANY ID {{user.company.id}}</h2>
    {% comment %} <table class="display" id="table_id">
        <thead>
            <tr class="text-center">
                <th scope="col">Nama</th>
                <th scope="col">Email</th>
                <th scope="col">Telpon</th>
                <th scope="col">Id Company</th>
            </tr>
        </thead>
        {% for profilperusahaan in profilperusahaan %}
        {% if user.company.id == profilperusahaan.id_company %}
        <tbody>
            <tr class="text-center">
                <td>{{profilperusahaan.name}}</td>
                <td>{{profilperusahaan.email}}</td>
                <td>{{profilperusahaan.telp}}</td>
                <td>{{profilperusahaan.id_company}}</td>
            </tr>
        </tbody>
        {% endif %}
        {% endfor %}
    </table> {% endcomment %}
</div>
{% endif %}

{% endblock %}